name: 🐞 Bug
description: Сообщить об ошибке/проблеме
title: "[BUG] <title>"
labels: ["Bug", "Needs Triage"]
body:
  - type: checkboxes
    attributes:
      label: Есть ли уже существующая проблема с этим?
      description: Пожалуйста, выполните поиск, чтобы узнать, существует ли уже проблема, с которой вы столкнулись.
      options:
        - label: Я искал(а) существующие проблемы
          required: true
  - type: textarea
    attributes:
      label: Описание
      description: Это подробное описание вашего бага
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Серьезность
      description: Атрибут, характеризующий влияние дефекта на работоспособность системы.
      options:
        - Блокирующая  ошибка, S1
        - Критическая ошибка, S2
        - Значительная ошибка, S3
        - Минорная ошибка, S4
        - Тривиальная ошибка, S5
      multiple: false
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Приоритет
      description: Атрибут, который указывает на очередность выполнения задачи.
      options:
        - High
        - Medium
        - Low
      multiple: false
    validations:
      required: false
  - type: textarea
    attributes:
      label: Фактический результат
      description: Краткое описание того, с чем вы столкнулись.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Ожидаемый результат
      description: Краткое описание того, что вы ожидали бы, чтобы произошло.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Шаги для воспроизведения
      description: Шаги для воспроизведения проблемы.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Окружение
      description: |
        Примеры:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
        - OS:
        - Node:
        - npm:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Есть ли что-то еще?
      description: |
        Ссылки? Справки? Все, что может предоставить нам больше контекста по поводу проблемы, с которой вы столкнулись!
        
        Совет: Вы можете прикрепить изображения или файлы журналов, выделив эту область и перетащив файлы.
    validations:
      required: false