name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "src,requirements.txt"
          target: "/home/deploy/observer"
      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/deploy/observer
            # Убедимся, что у нас есть права на выполнение операций
            chown -R deploy:deploy .
            # Активируем виртуальное окружение и устанавливаем зависимости
            su - deploy -c "cd /home/deploy/observer && source venv/bin/activate && pip install --no-cache-dir -r requirements.txt --default-timeout=60" || exit 1
            # Перезапускаем сервис
            systemctl restart observer.service || exit 1
            sleep 2
            systemctl is-active --quiet observer.service || (echo "Service failed to start" && exit 1)